### ISSUE TITLE
Timer for last level of chapter starting too early

### ISSUE THREAD

**Issue by Phate94** [srad/eLogical#7]
The timer starts running before the animation for the last level finishes.

**Comment by Elucidateqt** [comment]
fixed. rerolls now also reset the timer in the last level so that are more valuable lategame, give the players something to discover and feels smart about when "exploiting" something the designer forgot about (lunticular design). Also fixed various other similar timing-issues throughout the UI. For example the level-counter now increments only when the next level is loaded instead upon finishing the previous level and the sliding progress-animation now also is played only after interacting with the tutorial or skipping it.
